"""status reminder and archived columns  application tables

Revision ID: fddc9a569873
Revises: 65f4e40ee69e
Create Date: 2025-07-18 10:13:26.657709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fddc9a569873'
down_revision: Union[str, Sequence[str], None] = '65f4e40ee69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('status', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('needs_reminder', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'archived')
    op.drop_column('applications', 'needs_reminder')
    op.drop_column('applications', 'status')
    # ### end Alembic commands ###
